require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  
AllCops:
  TargetRubyVersion: 2.7.0
  Exclude:
    - '**/Rakefile'
    - 'db/**/*'
    - 'bin/**/*'
    - 'config/initializers/**/*'
    - 'tmp/**/*'
    - 'vendor/bundle/**/*'
    - 'config/application.rb'
    - 'config/environments/**/*'
    - 'spec/spec_helper.rb'
    - 'spec/rails_helper.rb'
    - 'spec/support/**/*'
    - node_modules/**/*

Metrics/AbcSize:
  Exclude:
    - 'spec/features/**/*'

Layout/LineLength:
  Max: 120 # Increase line length to 120